### ISSUE TITLE
General TODO

### ISSUE THREAD

**Issue by josh894** [GBADsInformatics/VisualizerDashboard#4]
- [x]  Include all percentages of all occurring flags (95% official, 5% imputed) 
- [x]  Fix title clipping at low window size
- [x]  Colourblind Friendly colours.
- [x] Larger dot sizes
- [ ] Dynamically display species per country

Extra:
- [x] Add a tab that allowed you to see summary stats for a country or species, e.g. Sengal would show the percentages of each category for all species appearing in the country.  And maybe even for one species over different decades.  For a species you could report overall percentages and maybe percentage breakdowns by decades.
